Fix for core dumped after creating any label
Had to add a NULL parameter at line 46, probably due to version issue in Qt since there's a reimplementation of the subElementRect function.

See:
https://doc.qt.io/qt-5/qcommonstyle.html

Error log:
[me@my-pc folder]$ labelme
[INFO] Loading config file from: /home/myuser/.labelmerc (__init__.py:72)
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/labelme/widgets/label_list_widget.py", line 46, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Aborted (core dumped)